added method to push imagedescription to quay.io
kiegroup/jenkins-pipeline-shared-libraries pull request #212
Opened 2022-08-02 10:24 UTC by mbiarnes

2022-08-02 11:50 UTC, radtriste commented on vars/cloud.groovy
> +* readmeFile = file that is the description for the image (i.e. path/README.md)
do no pass a file but a string content

2022-08-02 11:50 UTC, radtriste commented on vars/cloud.groovy
> +* registryPwd = pwd used when doing a login to quay.io (i.e. podman login -u=${REGISTRY_USER} -p=${REGISTRY_PWD} quay.io)
please use same signature as other methods. See https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/212/files#diff-7ddd125e7a802945e32ffe57f2b703f8134926ec3c3aad3fb84216fad1806c69R27

2022-08-02 11:50 UTC, radtriste commented on vars/cloud.groovy
> +void pushNewImageDesription(String readmeFile, String registryPwd, String imageId) {
rename to `updateQuayImageDescription`

2022-08-02 11:50 UTC, radtriste commented on vars/cloud.groovy
> +* imageId = image on quay.io with group (i.e. kiegroup/kie-server)
instead of `imageId`, other methods are using the `namespace/repository` vocabulary of Quay

2022-08-02 12:57 UTC, radtriste commented on vars/cloud.groovy
> +* Create CURL for pushing a new image description to quay.io
```suggestion
* Update image description on quay.io
```

2022-08-02 12:57 UTC, radtriste commented on vars/cloud.groovy
> +                description: readFile(file: "${descriptionString}")
```suggestion
                description: descriptionString
```

2022-08-02 13:23 UTC, radtriste commented on vars/cloud.groovy
> +        sh(script: "curl -H 'Content-type: application/json' -H 'Authorization: Bearer ${QUAY_TOKEN}' -X PUT --data-binary '@readmeFile.json' https://quay.io/api/v1/repository/${namespace}/${reposito
```suggestion
        writeJSON(file: 'description.json', json: json)
        archiveArtifacts(artifacts: 'description.json')
        sh(script: "curl -H 'Content-type: application/json' -H 'Authorization: Bearer ${QUAY_TOKEN}' -X PUT --data-binary '@description.json' https://quay.io/api/v1/repository/${namespace}/${repository}", returnStdout: true).trim()
```

2022-08-03 07:48 UTC, radtriste approved these changes

2022-08-04 14:35 UTC, mbiarnes commented
@radtriste added test

2022-08-04 14:54 UTC, radtriste commented on test/vars/CloudSpec.groovy
> +// updateQuayImageDescription
indentation

2022-08-04 14:54 UTC, radtriste approved these changes

2022-08-05 08:59 UTC, Ginxo requested changes
please check

2022-08-05 08:59 UTC, Ginxo commented on test/vars/CloudSpec.groovy
> +        groovyScript.updateQuayImageDescription('DESCRIPTION', 'namespace', 'repository', [token: 'TOKEN'])
to define additional cases for 

- ` [token: X, usernamePassword: Y]`
- ` [usernamePassword: Y]`
- ` []`

2023-08-04 07:58 UTC, radtriste approved these changes

2023-08-07 12:16 UTC, radtriste approved these changes

2023-08-07 12:16 UTC, merged