KOGITO-3135: adds new method for creating a release
kiegroup/jenkins-pipeline-shared-libraries pull request #266
Opened 2023-02-27 12:33 UTC by mbiarnes

2023-02-27 12:39 UTC, radtriste commented on vars/githubscm.groovy
> +        }
please create a `deleteRelease` method and let the "user" decide

2023-02-27 12:40 UTC, radtriste commented on vars/githubscm.groovy
> +        }
*decide whether it wants to delete if already existing

2023-02-28 11:20 UTC, radtriste commented on vars/githubscm.groovy
> +* Checks if a release already exists, removes it and creates a new
please update comment with new meaning

2023-02-28 11:20 UTC, radtriste commented on vars/githubscm.groovy
> +    def String description = "release ${tagName}"
```suggestion
    String description = "release ${tagName}"
```

2023-02-28 11:20 UTC, radtriste commented on vars/githubscm.groovy
> +    def String description = "release ${tagName}"
Also can we make the description a parameter of the method, with default to `Release ${tagName}`

2023-02-28 11:20 UTC, radtriste commented on vars/githubscm.groovy
> +        echo "removing release ${tagName}"
Useless I would say
```suggestion
```

2023-02-28 11:20 UTC, radtriste commented on vars/githubscm.groovy
> +    return status == 0
```suggestion
    return sh(script: "gh release view ${tagName}", returnStatus: true) == 0
```

2023-03-02 14:15 UTC, Ginxo requested changes
please provide tests for isReleaseExist

2023-03-02 14:47 UTC, mbiarnes commented
@Ginxo 
Done. Tests provided.

2023-03-02 15:40 UTC, Ginxo approved these changes
LGTM

2023-03-02 20:23 UTC, radtriste commented on vars/githubscm.groovy
> +
```suggestion
```

2023-03-02 20:23 UTC, radtriste commented on vars/githubscm.groovy
> +
```suggestion
```

2023-03-02 20:24 UTC, radtriste commented on vars/githubscm.groovy
> +
```suggestion
/*
* Checks whether a release exists on GitHub
*/
```

2023-03-02 20:24 UTC, radtriste commented on vars/githubscm.groovy
> +        exist =  sh(script: "gh release view ${tagName}", returnStatus: true) == 0
```suggestion
        exist = sh(script: "gh release view ${tagName}", returnStatus: true) == 0
```

2023-03-02 20:25 UTC, radtriste approved these changes

2023-03-02 20:59 UTC, merged