[BXMSPROD-2011] Added withKerberos utility method
kiegroup/jenkins-pipeline-shared-libraries pull request #270
Opened 2023-04-09 12:45 UTC by lampajr

2023-04-11 07:45 UTC, Ginxo requested changes
thanks for this, please check my comments

2023-04-11 07:46 UTC, lampajr commented on vars/util.groovy
> +    }
Thanks @Ginxo , I totally agree with you!

2023-04-11 09:35 UTC, lampajr commented on vars/util.groovy
> +    }
Updated

2023-04-12 06:21 UTC, Ginxo approved these changes
LGTM

2023-04-12 06:22 UTC, merged