NO-ISSUE - Output docker build logs to a file instead of standard output
kiegroup/jenkins-pipeline-shared-libraries pull request #307
Opened 2023-11-14 20:32 UTC by ricardozanini

Docker build can be really verbose duo to Cekit nature and the whole modules we use in our images. This pollutes the pipelines logs, making debug and troubleshooting quite a challenge. Instead, I've added an option to send this output to a log file, so the pipeline node can archive the result in the `post` stage. The file name has the image plus the platform suffix. Pretty easy to write a regex to archive it after the build.

This PR won't change the default behavior, but pipelines have the option to turnoff the image build logs now.

Do you guys know how do I test this?

2023-11-15 11:54 UTC, jstastny-cz approved these changes
LGTM.

`archiveArtifacts artifacts: '**/*-build.log', allowEmptyArchive: true` should do ...

2023-11-15 12:13 UTC, jstastny-cz commented
@ricardozanini wondering if the cekit tests can also store container logs ... or if they do and we just don't collect them. Because what is currently freezing are actualy the behave tests, and from there we have no log from the tested container :/

2023-11-16 06:41 UTC, jstastny-cz requested changes

2023-11-16 06:41 UTC, jstastny-cz commented on test/vars/CloudSpec.groovy
> +        1 * getPipelineMock("sh")("docker buildx build --push --sbom=false --provenance=false --platform PLATFORM -t IMAGE . > IMAGE-PLATFORM-build.log")
Just tested this, we need to replace all slashes at least, otherwise we're getting non-existent directory error.

2023-11-16 08:14 UTC, jstastny-cz commented on test/vars/CloudSpec.groovy
> +        1 * getPipelineMock("sh")("docker buildx build --push --sbom=false --provenance=false --platform PLATFORM -t IMAGE . > IMAGE-PLATFORM-build.log")
And also we should take care where we put the logs. Given that this is jenkins library and we know we might be running in docker container, we can put into workspace.

2023-11-16 08:14 UTC, jstastny-cz commented on test/vars/CloudSpec.groovy
> +        1 * getPipelineMock("sh")("docker buildx build --push --sbom=false --provenance=false --platform PLATFORM -t IMAGE . > IMAGE-PLATFORM-build.log")
And I am commenting on test, not impl, wonderful. I'll add a suggestion in the right place.

2023-11-16 08:15 UTC, jstastny-cz commented on vars/cloud.groovy
> +    sh "docker buildx build --push --sbom=false --provenance=false --platform ${platform} -t ${buildImageTag} .${outputToFile ? ' > ' + buildImageTag + '-' + platform + '-build.log' : ''}"
```suggestion
    def logFileName = (buildImageTag + '-' + platform + '-build.log')
        .replaceAll('/','_')
        .replaceAll(':','_')
    sh "docker buildx build --push --sbom=false --provenance=false --platform ${platform} -t ${buildImageTag} .${outputToFile ? ' 2> ' + "${WORKSPACE}/${logFileName}" : ''}"
```

2023-11-16 08:17 UTC, jstastny-cz commented on vars/cloud.groovy
> +    sh "docker buildx build --push --sbom=false --provenance=false --platform ${platform} -t ${buildImageTag} .${outputToFile ? ' > ' + buildImageTag + '-' + platform + '-build.log' : ''}"
Solving issues:
* `/` in path which would result in non-existent parent dir error.
* putting the log file into workspace, that is mapped from the host machine and does survive until post>always phase where we store artifacts.

2023-11-16 13:06 UTC, radtriste commented
> LGTM.
> 
> `archiveArtifacts artifacts: '**/*-build.log', allowEmptyArchive: true` should do ...

+1 should be added to the shared lib method if output to file

2023-11-16 17:57 UTC, ricardozanini commented
@jstastny-cz I think we are good now?

2023-11-16 18:16 UTC, jstastny-cz approved these changes
Indeed, thanks.

2023-11-17 12:33 UTC, merged